# callback instance:
#{
#  'inline_message_id': None,
#  'chat_instance': u'-490179135417304710',
#  'from_user': {
#       'username': u'MohGanji', 
#       'first_name': u'MoHaMMaD', 
#       'last_name': None, 
#       'id': 117990761, 
#       'language_code': u'en-US'
#   },
#   'message': {
#       'forward_from_chat': None, 
#       'new_chat_photo': None, 
#       'invoice': None, 
#       'text': u'New Report:\nFinglish: base\nFarsi: \u0628\u0633\nCorrected: \u0628\u0633\u0647', 
#       'sticker': None, 
#       'successful_payment': None, 
#       'pinned_message': None, 
#       'delete_chat_photo': None, 
#       'migrate_from_chat_id': None, 
#       'new_chat_members': None, 
#       'video': None, 
#       'left_chat_member': None, 
#       'chat': <telebot.types.Chat instance at 0x7f2f38106fc8>, 
#       'group_chat_created': None, 
#       'migrate_to_chat_id': None, 
#       'forward_date': None, 
#       'entities': None, 
#       'location': None, 
#       'photo': None, 
#       'document': None, 
#       'forward_from': None, 
#       'supergroup_chat_created': None, 
#       'edit_date': None, 
#       'content_type': 'text', 
#       'from_user': <telebot.types.User instance at 0x7f2f38106f80>, 
#       'date': 1507545273, 
#       'new_chat_member': None, 
#       'audio': None, 
#       'reply_to_message': None, 
#       'venue': None, 
#       'message_id': 2476, 
#       'caption': None, 
#       'contact': None, 
#       'channel_chat_created': None, 
#       'video_note': None, 
#       'voice': None, 
#       'new_chat_title': None
#   }, 
#   'data': u'accept',
#   'id': u'506766463387624646', 
#   'game_short_name': None
#}
